### PR TITLE
Add hospitalization 7daycases and 7dayincidences

### LINKED ISSUE #275: 7-Tage-Hospitalisierungsinzidenz
Du you already have an idea, whether it will be possible to provide the "7-Tage-Hospitalisierungsinzidenz" in your API? I'd like to show it in my Scriptable-Widget.

### PR DESCRIPTION
**Pull request by Rubber1Duck**
This will add the hospitalization 7-day-cases and 7-day-incidences, as some user requests in #275 
I don't know if this is a clean programming style, but I still struggle with JS and TS, but it works. 
Fix #275 
hospitalization
hospi-states

### CODE REVIEW

**Comment by Rubber1Duck** [comment]
@marlon360 Hi Marlon, some users asked about this enhancment ( #275 ). So I sat down and put it into practice.
It took me many many hours of try & error to write this enhancement with my modest TS (JS) knowledge. I like to do it, and I have the time, but no feedback at all is kind of frustrating and worse than negative feedback!
I am currently working on the history of hospitalization rates and I would like to know if it is worth going ahead!
cu
Peter (Rubber1Duck)

**Comment by marlon360** [comment]
Hi @Rubber1Duck!
Thanks for the PR. I am back from vacation and will look into it in the next days.

**Comment by marlon360** [comment]
I want to structure the data differently:

In the `/germany` endpoint we only add the `cases7days` and `incidence7days` for `"Bundesgebiet"`.
In the `/germany/age-groups` we add the age groups for the hospitalization under the property `hospitalization` for `"Bundesgebiet"`.

The same pattern applies to `/states` and `/states/age-groups`

**Comment by marlon360** [comment]
- [x] age-groups for states
- [x] update documentation

**Review by marlon360 — APPROVED** [review]

**Pull request merged**
