### PR TITLE
Fix vaccination history

### PR DESCRIPTION
**Pull request by laurenzfg**
RKI changed headers

This fixes parts of issue #237

### CODE REVIEW

**Review by Rubber1Duck — APPROVED** [review]
Tested and work as designed!

**Comment by Rubber1Duck** [comment]
@marlon360 i know that you are very busy at the time, but please approve and merge this PR a.s.a.p. because /vaccination/history do not work again (since yesterday!) and hopefully you find some time to answer my question in https://github.com/marlon360/rki-covid-api/issues/237#issuecomment-859402467

**Comment by laurenzfg** [comment]
If you @marlon360 decide to include the latest history entry in the coverage endpoint (I'd find that very useful) you may merge #239 instead.

**Comment by laurenzfg** [comment]
Closed, project accepted #239

**Pull request closed without merging**
