### PR TITLE
New vaccination parser

### LINKED ISSUE #153: Structure of vaccination xlsx file is changed
The strcture of source vaccination xlsx file is changed. The parser must be rewitten!
vaccination

### PR DESCRIPTION
**Pull request by Rubber1Duck**
Fix #153

### CODE REVIEW

**Review by gregorsarnow — APPROVED** [review]
LGTM

**Comment by gregorsarnow** [comment]
Just build it to host it myself and noticed that the attribute `administeredVaccinations` is missing in the response 
[response.txt](https://github.com/marlon360/rki-covid-api/files/6286752/response.txt)

Edit: Maybe the issue is line 171 :man_shrugging:

>         "totvaccination",

**Comment by Rubber1Duck** [comment]
> 
> 
> Just build it to host it myself and noticed that the attribute `administeredVaccinations` is missing in the response
> [response.txt](https://github.com/marlon360/rki-covid-api/files/6286752/response.txt)
> 
> Edit: Maybe the issue is line 171 🤷‍♂️
> 
> > ```
> >     "totvaccination",
> > ```

You are right! will patch it.

Thanks a lot

**Comment by Rubber1Duck** [comment]
administeredVaccinations is fixed
vaccination_example2

**Comment by beyerleinf** [comment]
Looks good, thanks @Rubber1Duck! :)

Are you sure it's a good idea to change the type of the properties that were dropped by the RKI? I could imagine it wouldn't break as many apps if we just leave them as zero.

**Comment by Rubber1Duck** [comment]
> 
> 
> Looks good, thanks @Rubber1Duck! :)
> 
> Are you sure it's a good idea to change the type of the properties that were dropped by the RKI? I could imagine it wouldn't break as many apps if we just leave them as zero.

I am unsure if i am sure :-) I had the same thoughts. And maybe it is the better way to set this to "Null" (empty).
Okay, i think thats the better way.... will patch this.

**Comment by beyerleinf** [comment]
Do you mean null as in `null` or as in `0`? :D

**Review by beyerleinf — CHANGES_REQUESTED** [review]
I hate to be that guy but I think the number zero would be safer for the users of this API. However, if I'm the only one that thinks that way, I'm fine with it :)

**Comment by Rubber1Duck** [comment]
I think i should be clear for all that this information is not available, so null should be the better part.
do you remember the case that some fields at "Bund" are filled with "-", there also this fields are changed to null, and that i think was okay!
Lets see what @marlon360 opinion is. to sitch this to 0 is not a big deal :-) But unfortnatly he is realy very busy at the moment

**Review by beyerleinf — APPROVED** [review]
In that case, all looks good! :)

**Review by marlon360 — APPROVED** [review]
Great work! Thanks!

**Pull request merged**
