### PR TITLE
fix maps with legend on selfhosted api

### LINKED ISSUE #316: New maps with legend are not working if selfhosted
on selfhosted API the new map feature with legend are not working as expected!
the resulting image looks like this
map

i start to add the ttf fonts in the Dockercontainer with this result

map2

looks fine but the date is not in the right format!
After some search with our friend google i found out the following By default --with-intl=small-icu is used to build node, which contains just the en-US locale! (see [https://github.com/nodejs/node/issues/8500](https://github.com/nodejs/node/issues/8500) ) (for node <=V12, for node >V12 this is not the case!)
the solution is to add a additional module `full-icu` and a ENV. tried it with this image

map3

looks fine!

now i will make the PR.

### PR DESCRIPTION
**Pull request by Rubber1Duck**
fix #316

### CODE REVIEW

**Comment by marlon360** [comment]
Is it possible to remove "full-icu" when we update the container to node:16?

**Comment by Rubber1Duck** [comment]
> 
> 
> Is it possible to remove "full-icu" when we update the container to node:16?

i think so! As i understood  the missing locales are only in node versions <=12 

I will test it and if it succeeds I will change the PR if you wish

**Comment by Rubber1Duck** [comment]
I have just tested node:16 and as expected this is working well without modul full-icu, but the resulting uncompressed image will grow up ~ 18MB compared to node:12 with modul fill-icu (the fonts must be installed in both cases!)
Uncompressed image sizes
baseimage 12-alpine3.12 with modul full-icu 515MB
baseimage 16-alpine3.12 without modul full-icu 533MB

@marlon360 witch solution do you want?

**Comment by marlon360** [comment]
> I have just tested node:16 and as expected this is working well without modul full-icu, but the resulting uncompressed image will grow up ~ 18MB compared to node:12 with modul fill-icu (the fonts must be installed in both cases!) Uncompressed image sizes baseimage 12-alpine3.12 with modul full-icu 515MB baseimage 16-alpine3.12 without modul full-icu 533MB
> 
> @marlon360 witch solution do you want?

@Rubber1Duck Thanks for investigating the sizes!

Let's go with the node:16 image

**Review by marlon360 — CHANGES_REQUESTED** [review]
Thanks!
But I think the package-lock.json doesn't need any changes.

**Comment by Rubber1Duck** [comment]
hmmm but i get this messages at npm install
```
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
```

and after that the packeage-lock.json file is updated!

**Comment by Rubber1Duck** [comment]
okay downgrading npm to 6.14.15 fix this!

PR will be updated

**Comment by marlon360** [comment]
Oh okay, let's look at the npm problem in a separate PR.

**Review by marlon360 — APPROVED** [review]

**Comment by Rubber1Duck** [comment]
I dont think thats a realy problem, all went well. when building the docker image the warning is showed, but it is only a warning.
this can be avoid by inserting `npm -g install npm@6.14.15` in the dockerfile, but this is not a "must"

**Pull request merged**
