### PR TITLE
color and range definitions should be only at one point

### PR DESCRIPTION
**Pull request by Rubber1Duck**
color and range definitions should be only at one point (configuration/colors.ts)

### CODE REVIEW

**Comment by marlon360** [comment]
Good idea @Rubber1Duck!
Maybe let's try adding the legend dynamically. Which means looping through the ranges and adding a `<text>` and `<rect>` for each entry. And also increase y-position with each entry.

**Comment by Rubber1Duck** [comment]
i will do my very best .................

in my opinion it makes also sense to save on the two new functions to build the maps with legend, only the return value is different to the functions to build only the map. with a new parameter and a simple if else this can be done! are you interested?  if yes then i will do another PR. Waiting for your reply for this!

**Comment by Rubber1Duck** [comment]
done

**Comment by Rubber1Duck** [comment]
done, now realy :-)

**Comment by Rubber1Duck** [comment]
thank you for your trust

**Comment by Rubber1Duck** [comment]
@marlon360 did you find some time to have a look on this

**Review by marlon360 — APPROVED** [review]

**Pull request merged**
