### PR TITLE
R-Value now extracted from xlsx file

### PR DESCRIPTION
**Pull request by Rubber1Duck**

### CODE REVIEW

**Comment by Rubber1Duck** [comment]
so is besser :-)

**Review by marlon360 — APPROVED** [review]

**Review by marlon360 — CHANGES_REQUESTED** [review]
Hi @Rubber1Duck 

Could you change this in the README.md too?

**Comment by Rubber1Duck** [comment]
of corse, one moment

**Review by marlon360 — APPROVED** [review]

**Comment by marlon360** [comment]
Thanks @Rubber1Duck

**Pull request merged**
